### ISSUE TITLE
unable to get AllergyIntolerence from FHIR for a patient

### ISSUE THREAD

**Issue by kchopper** [fhir-crucible/fhir_client#115]
`@fhir_client.search(FHIR::AllergyIntolerence, search: { parameters: { patient: @patient.id }}).resource`

`Completed 500 Internal Server Error in 11458ms (ActiveRecord: 2.1ms)
NameError (uninitialized constant FHIR::AllergyIntolerence)`

**Comment by jawalonoski** [comment]
You spelled it wrong. `AllergyIntolerance`. See: http://hl7.org/fhir/allergyintolerance.html

```ruby
server_url = 'http://hapi.fhir.org/baseR4'
client = FHIR::Client.new(server_url)
# the search below fails with AllergyIntolerance spelled incorrectly
reply = client.search(FHIR::AllergyIntolerence)
# the search below succeeds with AllergyIntolerancd spelled correctly
reply = client.search(FHIR::AllergyIntolerance)
```
