### ISSUE TITLE
Is there any option to get patient information from NHS server

### ISSUE THREAD

**Issue by uzaif313** [fhir-crucible/fhir_client#118]
Anyone have idea about how to retrieve data from NHS server.
I have patient information store like firstname, lastname, dob etc.

Let me know if any one have idea about that.

**Comment by jawalonoski** [comment]
You would have to get the FHIR server endpoint URL from the NHS, as well as some type of authentication and authorization credentials from the NHS.

Assuming you've done that, you should be able to configure the client URL and security.

For example, if the NHS uses a FHIR server that requires OAuth2 -- and I have no idea whether they do or do not -- you could reference this example from the README:

https://github.com/fhir-crucible/fhir_client#oauth2-support

**Comment by uzaif313** [comment]
@jawalonoski Thanks for detail information.
