### ISSUE TITLE
Using with SMART on FHIR Integration

### ISSUE THREAD

**Issue by fulstop** [fhir-crucible/fhir_client#121]
I'm new to FHIR and SMART on FHIR, and would like some guidance as to how to get this working after the initial Authorization (see reference [here](https://docs.smarthealthit.org/tutorials/authorization/)).

Can this gem be used to bypass the JS Auth implementation to do everything from the back end?

Also, when following the official SMART on FHIR App Launcher [directions](http://launch.smarthealthit.org/?auth_error=&fhir_version_1=r4&fhir_version_2=r2&iss=&launch_ehr=1&launch_url=http%3A%2F%2Flocalhost%3A3000%2Fsmart&patient=&prov_skip_auth=1&prov_skip_login=1&provider=499165&pt_skip_auth=1&public_key=&sb=&sde=&sim_ehr=1&token_lifetime=15&user_pt=) with the OAuth2 strategy from the [README](https://github.com/fhir-crucible/fhir_client#oauth2-support), I get the following Ruby error:
```ruby
Missing client_assertion_type parameter
```
at the following line:
```ruby
client.set_oauth2_auth(client_id, client_secret, options[:authorize_url] ,options[:token_url], options[:site])
```

there are `options` values for all keys except `options[:site]`.

I'm likely doing something completely wrong. Any guidance would be much appreciated.

**Comment by radamson** [comment]
You'll need some sort of server in addition to the `FHIR::Client` to handle the [redirects](http://www.hl7.org/fhir/smart-app-launch/#smart-authorization-and-resource-retrieval) back from the authorization server.  There's more than one way to do it, but you can see an example of using the `FHIR::Client` with SMART on FHIR [here in Inferno](https://github.com/onc-healthit/inferno/blob/master/lib/app/modules/smart/standalone_launch_sequence.rb).  This workflow uses a [RestClient](https://github.com/rest-client/rest-client) to walk through the authorization sequence before setting up the `FHIR::Client` up with the access token using [`#set_bearer_token`](https://github.com/fhir-crucible/fhir_client/blob/master/lib/fhir_client/client.rb#L136).

@jawalonoski might have some other examples or ones that use `#set_oauth2_auth`

**Comment by jawalonoski** [comment]
Another older archived example that probably would need to be updated is here: https://github.com/mitre/scorecard_app

The primary endpoint and redirect is here: https://github.com/mitre/scorecard_app/blob/master/app.rb#L52

And the launch endpoint is here: https://github.com/mitre/scorecard_app/blob/master/app.rb#L131

The semi-confusing thing about this app that you might notice if you look too deep, is that it is both a SMART on FHIR app and a FHIR microservice. For the purposes if this question, you can ignore the microservice aspects.

**Comment by fulstop** [comment]
Thanks for the guidance and resources!
