### ISSUE TITLE
OAuth URL structure should provide complete URLs

### ISSUE THREAD

**Issue by jmandel** [fhir-crucible/fhir_client#3]
The following [convenience structure](https://github.com/fhir-crucible/fhir_client/blob/d59de3372268a61915db07bfd89c8ef67521a524/lib/client_interface.rb#L84):

```
    options = {
      :site => baseUrl,
      :authorize_url => authorizePath,
      :token_url => tokenPath,
      :raise_errors => false
    }
```

is overly restrictive: it assumes that the `authorize` and `token` URLs must always share the same `site` -- but this isn't in general a reliable assumption. It would be better to capture full URLs here for authorize, token, and register.

**Comment by jawalonoski** [comment]
Fixed with latest pull request.
