### ISSUE TITLE
does not switch to JSON

### ISSUE THREAD

**Issue by dhf0820** [fhir-crucible/fhir_client#33]
connecting to the cerner sandbox https://fhir-open.sandboxcernerpowerchart.com/may2015/d075cf8b-3261-481d-97e5-ba6c48d3b41f/Patient/2744010 fails unless I hard code the change of the default to json.

Is there a way on initialization to specify JSON or XML.  Cerner only supports JSON.

**Comment by dhf0820** [comment]
I did find where the default values are set in the initializer.  After initializing I set them to JSON and it works with Cerner.  I am not sure however I suspect the conformance is not called unless using oauth.  I am using the open one currently with no authentication.

**Comment by jawalonoski** [comment]
This works:

```ruby
client = FHIR::Client.new('https://fhir-open.sandboxcernerpowerchart.com/may2015/d075cf8b-3261-481d-97e5-ba6c48d3b41f')
conformance = client.conformanceStatement
patient = client.read(FHIR::Patient, '2744010')
```
Can you provide an example the code you're having problems with?

**Comment by jawalonoski** [comment]
We've recently applied some fixes for JSON issues been reported. Can you confirm that you are still seeing this issue?

**Comment by jawalonoski** [comment]
In case future readers find this issue, you can also switch to JSON using the `default_json` method.

For example:

```ruby
client = FHIR::Client.new(url)
client.default_json
# do stuff with the client using JSON
```
