### ISSUE TITLE
response element in middle of patient

### ISSUE THREAD

**Issue by dhf0820** [fhir-crucible/fhir_client#34]
When I do a Patient.read I get this response in the middle of th patient.  I do not get it on any other models.

     @resource_class=FHIR::Patient,
     @response=
      {:code=>"200",
       :headers=>
        {"cache-control"=>"private",
         "content-length"=>"3245",
         "content-type"=>"application/json+fhir; charset=utf-8",
         "server"=>"Microsoft-IIS/7.5",
         "x-aspnet-version"=>"4.0.30319",
         "x-powered-by"=>"ASP.NET",
         "date"=>"Wed, 06 Jul 2016 04:35:43 GMT"},
       :body=>
        "{\"resourceType\":\"Patient\",\"id\":\"19\",\"text\":{\"status\":\"generated\",\"div\":\"<div>\\n<p><table width=\\\"500\\\">\\n<tbody>\\n<tr>\\n            <td>Name</td>\\n            <td>Allison  <b>Allscripts</b> (&quot;Allison&quot;)</td>\\n          </tr>\\n<tr>\\n            <td>Address</td>\\n            <td>34 Smith Mt. Road. Apartment 1 Springfield IL 60654     </td>\\n          </tr>\\n<tr>\\n            <td>Contacts</td>\\n            <td>Home: (312) 555-1112. Work: (847) 608-3515x4357 </td>\\n          </tr>\\n<tr>\\n            <td>Id:19</td>\\n            <td>MRN: ZZZTW01 </td>\\n          </tr>\\n</tbody>\\n      </table>\\n</p>    </div>\"},\"extension\":[{\"url\":\"http://hl7.org/fhir/StructureDefinition/us-core-race\",\"valueCodeableConcept\":{\"coding\":[{\"system\":\"OBM\",\"code\":\"0\",\"display\":\" \"}]}},{\"url\":\"http://hl7.org/fhir/StructureDefinition/us-core-ethnicity\",\"valueCodeableConcept\":{\"coding\":[{\"system\":\"OBM\",\"code\":\"0\",\"display\":\"\"}]}},{\"url\":\"http://hl7.org/fhir/StructureDefinition/us-core-religion\",\"valueCodeableConcept\":{\"coding\":[{\"code\":\"          \",\"display\":\" \"}]}}],\"identifier\":[{\"type\":{\"coding\":[{\"code\":\"ZZZTW01\",\"display\":\"ZZZTW01\",\"userSelected\":false},{\"code\":\"4         \",\"display\":\"Other\",\"userSelected\":false}],\"text\":\"TouchWorks MRN\"},\"system\":\"dummy identifier system\",\"value\":\"ZZZTW01\",\"assigner\":{\"reference\":\"Organization/3\"}}],\"active\":true,\"name\":[{\"text\":\"Allscripts,Allison \",\"family\":[\"Allscripts\"],\"given\":[\"Allison\"],\"prefix\":[\"     \"],\"suffix\":[\"     \"]}],\"telecom\":[{\"system\":\"phone\",\"value\":\"(312) 555-1112\",\"use\":\"home\"},{\"system\":\"phone\",\"value\":\"(847) 608-3515x4357 \",\"use\":\"work\"},{\"system\":\"fax\",\"value\":\"(708) 555-1001\"},{\"system\":\"email\",\"value\":\"allison@allscripts.com\"}],\"gender\":\"female\",\"birthDate\":\"1973-03-05\",\"deceasedBoolean\":false,\"address\":[{\"text\":\"34 Smith Mt. Road. Apartment 1 Springfield IL 60654      USA\",\"line\":[\"34 Smith Mt. Road.\",\"Apartment 1\"],\"city\":\"Springfield\",\"state\":\"IL\",\"postalCode\":\"60654     \",\"country\":\"US\"}],\"maritalStatus\":{\"coding\":[{\"system\":\"http://hl7.org/fhir/v3/vs/MaritalStatus\",\"code\":\"W\",\"display\":\"Widowed\"}]},\"multipleBirthBoolean\":false,\"contact\":[{\"relationship\":[{\"coding\":[{\"code\":\"4         \",\"display\":\"Other\"}]}],\"name\":{\"text\":\"Washington George\",\"family\":[\"Washington\"],\"given\":[\"George\"]},\"telecom\":[{\"system\":\"other\",\"value\":\"(312) 555-1101\",\"use\":\"home\"},{\"system\":\"other\",\"value\":\"(773) 555-1201x1101\",\"use\":\"work\"}],\"address\":{\"line\":[\"123 Waulnut Street\",\"Apartment 2E\"],\"city\":\"dummy address city\",\"state\":\"dummy address state\",\"postalCode\":\"dummy address postal code\",\"country\":\"dummy address country\"}},{\"relationship\":[{\"coding\":[{\"code\":\"4         \",\"display\":\"Other\"}]}],\"name\":{\"text\":\"Adams Abigail\",\"family\":[\"Adams\"],\"given\":[\"Abigail\"]},\"telecom\":[{\"system\":\"other\",\"value\":\"(312) 555-7701x8850\",\"use\":\"work\"},{\"system\":\"other\",\"value\":\"(847) 555-9901\",\"use\":\"home\"}],\"address\":{\"line\":[\"123 Main Street\",\"Apartment 41\"],\"city\":\"dummy address city\",\"state\":\"dummy address state\",\"postalCode\":\"dummy address postal code\",\"country\":\"dummy address country\"}}],\"communication\":[{\"language\":{\"coding\":[{\"system\":\"ISO-639-2\",\"code\":\"en\",\"display\":\"English\"}]}}],\"careProvider\":[{\"reference\":\"Practitioner/53\",\"display\":\"Allscripts,Family Medicine \"}]}"}>,
   @security_headers={},

The call is patient = FHIR::Patient.read(@patient_number)

**Comment by arscan** [comment]
We attach a client reference to the resources that are returned because it allows users to then issue another request using the same client used to get that resource (like ```patient.destroy``` or ```patient.update```).  This is mainly necessary for API users that have multiple clients pointing to different servers.

The downside to that is that all of the resources that the API returns now will print out a whole bunch of details associated with the client used to get the request if you are trying to debug them.  In your example, ```patient.client``` will have all the information about the client that you used to get that patient.  One of the things that the client saves is the last reply, which we use in Crucible to inspect some of the details of the request for debugging purposes.  It looks like the information that you copy/pasted in here is from that reply, which is stored in ```patient.client.reply```.

Given that background, it would make sense that response would show up in the middle of the patient, specifically within ```patient.client.reply```.  However, I don't know why it would only show up in the ```FHIR::Patient``` resource for you.  Could you try ```find```ing another resource type, and seeing if it has a ```client.reply``` as well?  I'm having trouble replicating that problem.

Do you have a problem with us storing that client reference in the resources that we return?  I agree that it makes printing out resources pretty cluttered when debugging.  I usually do something like ```print patient.to_xml```, which only shows patient information.

**Comment by dhf0820** [comment]
I just did it on an observation.  This is done with a search  to get all of the for a patient.  I then pull a specific and get this:

#<FHIR::Observation:0x007fd5b24410a8
 @bodySite=nil,
 @category=nil,
 @code=
  #<FHIR::CodeableConcept:0x007fd5b242f6f0
   @coding=
    [#<FHIR::Coding:0x007fd5b242f358
      @code="2823-3",
      @display="POTASSIUM:SCNC:PT:SER/PLAS:QN:",
      @extension=[],
      @id=nil,
      @system="http://loinc.org",
      @userSelected=nil,
      @version=nil>,
     #<FHIR::Coding:0x007fd5b242e980
      @code="108252007",
      @display="Laboratory procedure (procedure)",
      @extension=[],
      @id=nil,
      @system="http://snomed.info/sct",
      @userSelected=nil,
      @version=nil>],
   @extension=[],
   @id=nil,
   @text="Potassium Lvl">,
 @comment=nil,
 @component=[],
 @contained=[],
 @dataAbsentReason=nil,
 @device=nil,
 @effectiveDateTime=nil,
 @effectivePeriod=nil,
 @encounter=
  #<FHIR::Reference:0x007fd5b1e53cb8
   @display=nil,
   @extension=[],
   @id=nil,
   @reference="Encounter/2951906">,
 @extension=[],
 @id="M4637260",
 @identifier=[],
 @implicitRules=nil,
 @interpretation=
  #<FHIR::CodeableConcept:0x007fd5b242d508
   @coding=
    [#<FHIR::Coding:0x007fd5b242d170
      @code="AA",
      @display=
       "Very abnormal (applies to non-numeric units, analogous to panic limits for numeric units)",
      @extension=[],
      @id=nil,
      @system="http://hl7.org/fhir/v2/0078",
      @userSelected=nil,
      @version=nil>],
   @extension=[],
   @id=nil,
   @text="CRIT">,
 @issued="2015-04-17T06:40:38.000Z",
 @language=nil,
 @local_method=nil,
 @meta=
  #<FHIR::Meta:0x007fd5b2440680
   @extension=[],
   @id=nil,
   @lastUpdated="2015-10-16T07:17:23.000Z",
   @profile=[],
   @security=[],
   @tag=[],
   @versionId="17-4637259">,
 @modifierExtension=[],
 @performer=[],
 @referenceRange=
  [#<FHIR::Observation::Referencerange:0x007fd5b1e53740
    @age=nil,
    @extension=[],
    @high=
     #<FHIR::Quantity:0x007fd5b1e52d90
      @code="meq/L",
      @comparator=nil,
      @extension=[],
      @id=nil,
      @system="http://unitsofmeasure.org",
      @unit=nil,
      @value=5.1>,
    @id=nil,
    @low=
     #<FHIR::Quantity:0x007fd5b1e534e8
      @code="meq/L",
      @comparator=nil,
      @extension=[],
      @id=nil,
      @system="http://unitsofmeasure.org",
      @unit=nil,
      @value=3.5>,
    @meaning=nil,
    @modifierExtension=[],
    @text=nil>],
 @related=[],
 @specimen=nil,
 @status="final",
 @subject=
  #<FHIR::Reference:0x007fd5b242c130
   @display=nil,
   @extension=[],
   @id=nil,
   @reference="Patient/2744010">,
 @text=
  #<FHIR::Narrative:0x007fd5b242fd58
   @div=
    "<div><p><b>Observation</b></p><p><b>Patient</b>: 2744010</p><p><b>Status</b>: Auth (Verified)</p><p><b>Code</b>: Potassium Lvl</p><p><b>Result</b>: 2.34 mEq/L</p><p><b>Risk Level</b>: Very abnormal (applies to non-numeric units, analogous to panic limits for numeric units)</p><p><b>Date</b>: 2015-04-17T06:24:00.000Z</p><p><b>Risk Level Detail</b>: Low: 3.50 mEq/L High: 5.10 mEq/L</p></div>",
   @extension=[],
   @id=nil,
   @status="generated">,
 @valueAttachment=nil,
 @valueCodeableConcept=nil,
 @valueDateTime=nil,
 @valuePeriod=nil,
 @valueQuantity=
  #<FHIR::Quantity:0x007fd5b242dda0
   @code="meq/L",
   @comparator=nil,
   @extension=[],
   @id=nil,
   @system="http://unitsofmeasure.org",
   @unit=nil,
   @value=2.34>,
 @valueRange=nil,
 @valueRatio=nil,
 @valueSampledData=nil,
 @valueString=nil,
 @valueTime=nil>


The difference is the search for a patient does not work on any of the sites I am testing with (Cerner, Epic and AllScripts.  On can get the read to work and then I get the bundle no entries.  I save the raw data and do not want the client information or anything except the actual patient record.  

I can nil out those elements I do not want and should get what I want.  Though it is odd they are different.

**Comment by jawalonoski** [comment]
I'll be submitting a change that fixes this.
