### ISSUE TITLE
Cerner Immunization missing the vaccine

### ISSUE THREAD

**Issue by dhf0820** [fhir-crucible/fhir_client#35]
this is returned from the cerner sandbox:

{
    "resourceType": "Bundle",
    "id": "04eeda50-049a-459e-8818-0c57df0eff24",
    "type": "searchset",
    "base": "https://fhir-open.sandboxcernerpowerchart.com/may2015/d075cf8b-3261-481d-97e5-ba6c48d3b41f",
    "total": 1,
    "link": [
        {
            "relation": "self",
            "url": "https://fhir-open.sandboxcernerpowerchart.com/may2015/d075cf8b-3261-481d-97e5-ba6c48d3b41f/Immunization?patient=2744010"
        }
    ],
    "entry": [
        {
            "resource": {
                "resourceType": "Immunization",
                "id": "M3869433",
                "text": {
                    "status": "generated",
                    "div": "<div><p><b>Immunization</b></p><p><b>Date</b>: 2014-09-25T21:00:00.000Z</p><p><b>Given</b>: Yes</p><p><b>Administered by</b>: Kolm, Margaret</p><p><b>Site</b>: left arm</p><p><b>Route</b>: IM</p></div>"
                },
                "date": "2014-09-25T21:00:00.000Z",
                "vaccineType": {
                    "coding": [
                        {
                            "system": "http://www2a.cdc.gov/vaccines/iis/iisstandards/vaccines.asp?rpt=cvx",
                            "code": "88"
                        }
                    ],
                    "text": "Fluzone"
                },
                "patient": {
                    "reference": "Patient/2744010"
                },
                "wasNotGiven": false,
                "reported": false,
                "performer": {
                    "reference": "Practitioner/2770007",
                    "display": "Kolm, Margaret"
                },
                "encounter": {
                    "reference": "Encounter/2457918"
                },
                "manufacturer": {
                    "reference": "Organization/661540",
                    "display": "SANOFI WINTHROP PHARMACEUTICALS"
                },
                "lotNumber": "4264a",
                "expirationDate": "2015-09-25",
                "site": {
                    "coding": [
                        {
                            "system": "http://hl7.org/fhir/v3/ActSite",
                            "code": "LA",
                            "display": "left arm"
                        }
                    ],
                    "text": "left arm"
                },
                "route": {
                    "text": "IM"
                },
                "doseQuantity": {
                    "value": 0.1,
                    "units": "mL"
                }
            }
        }
    ]
}

this is what is parsed in to immunization:
#<FHIR::Immunization:0x007fa8ac9eea38
 @contained=[],
 @date="2014-09-25T21:00:00.000Z",
 @doseQuantity=
  #<FHIR::Quantity:0x007fa8ac9ff108
   @code=nil,
   @comparator=nil,
   @extension=[],
   @id=nil,
   @system=nil,
   @unit=nil,
   @value=0.1>,
 @encounter=
  #<FHIR::Reference:0x007fa8ac98cdb0
   @display=nil,
   @extension=[],
   @id=nil,
   @reference="Encounter/2457918">,
 @expirationDate="2015-09-25",
 @explanation=nil,
 @extension=[],
 @id="M3869433",
 @identifier=[],
 @implicitRules=nil,
 @language=nil,
 @location=nil,
 @lotNumber="4264a",
 @manufacturer=
  #<FHIR::Reference:0x007fa8ac98ca18
   @display="SANOFI WINTHROP PHARMACEUTICALS",
   @extension=[],
   @id=nil,
   @reference="Organization/661540">,
 @meta=nil,
 @modifierExtension=[],
 @note=[],
 @patient=
  #<FHIR::Reference:0x007fa8ac98e728
   @display=nil,
   @extension=[],
   @id=nil,
   @reference="Patient/2744010">,
 @performer=
  #<FHIR::Reference:0x007fa8ac98d7b0
   @display="Kolm, Margaret",
   @extension=[],
   @id=nil,
   @reference="Practitioner/2770007">,
 @reaction=[],
 @reported=false,
 @requester=nil,
 @route=
  #<FHIR::CodeableConcept:0x007fa8ac9ff590
   @coding=[],
   @extension=[],
   @id=nil,
   @text="IM">,
 @site=
  #<FHIR::CodeableConcept:0x007fa8ac98c270
   @coding=
    [#<FHIR::Coding:0x007fa8ac98c220
      @code="LA",
      @display="left arm",
      @extension=[],
      @id=nil,
      @system="http://hl7.org/fhir/v3/ActSite",
      @userSelected=nil,
      @version=nil>],
   @extension=[],
   @id=nil,
   @text="left arm">,
 @status=nil,
 @text=
  #<FHIR::Narrative:0x007fa8ac98f920
   @div=
    "<div><p><b>Immunization</b></p><p><b>Date</b>: 2014-09-25T21:00:00.000Z</p><p><b>Given</b>: Yes</p><p><b>Administered by</b>: Kolm, Margaret</p><p><b>Site</b>: left arm</p><p><b>Route</b>: IM</p></div>",
   @extension=[],
   @id=nil,
   @status="generated">,
 @vaccinationProtocol=[],
 @vaccineCode=nil,
 @wasNotGiven=false>

The vaccineCode is nil because they use vaccineType. THey use the final ballot 1.02.  Is there an easy way to get access to the vaccineType they use?

**Comment by jawalonoski** [comment]
Final ballot of 1.0.2 (DSTU2) is also supposed to be `vaccineCode` (see http://hl7.org/fhir/DSTU2/immunization.html), so if that is the correct version number then they have a bug.

Against DSTU2 servers, you should use the DSTU2 branch of fhir_client here: https://github.com/fhir-crucible/fhir_client/tree/dstu2

But to answer your question -- no, there is no way easy way to access the `vaccineType` they include.

**Comment by dhf0820** [comment]
Their sandbox is 1.0.2 their production is 0.5

**Comment by jawalonoski** [comment]
Regarding the version numbers, that makes sense. 

The only way to access `vaccineType` will be from parsing the response and accessing it manually... something like:

```ruby
reply = client.read(FHIR::Immunization, id, FHIR::Formats::ResourceFormat::RESOURCE_JSON)
json = JSON.parse(reply.response)
raw_vaccineType = json['vaccineType']
vaccineType = FHIR::CodeableConcept.new(raw_vaccineType)
```

**Comment by dhf0820** [comment]
Thank you for the reply. This can be closed
