### ISSUE TITLE
Question regarding observations

### ISSUE THREAD

**Issue by dhf0820** [fhir-crucible/fhir_client#5]
I notice items like referenceRange are not filled in when the observation is displayed. Yet the values are in the xml.

I am using this to learn more about FHIR.

**Comment by jawalonoski** [comment]
Quick testing of our serialization/deserialization of `Observation.referenceRange` seems to function properly (see below). Can you provide a failing example? Or am I misunderstanding the issue?

```ruby
xml = '<?xml version="1.0" encoding="UTF-8"?><Observation xmlns="http://hl7.org/fhir"><referenceRange><low><value value="1.0"/></low><high><value value="10.0"/></high></referenceRange></Observation>'
obs = FHIR::Observation.from_xml(xml)
obs.to_xml
```
