### ISSUE TITLE
Trailing Slashes?

### ISSUE THREAD

**Issue by jawalonoski** [fhir-crucible/fhir_client#57]
Submitted via email:

> I’m testing my FHIR server against Crucible. It’s failing all the tests for resource-level history
> interaction because the URL that crucible is hitting has a trailing slash, which our server isn’t expecting:
> https://.../fhir/AllergyIntolerance/3/_history/
> 
> The trailing slash doesn’t seem to be strictly consistent with the standard:
> http://hl7.org/fhir/DSTU2/http.html#history
> 
> Can you change the tests to not include that trailing slash?

**Comment by arscan** [comment]
Fixed in https://github.com/fhir-crucible/fhir_client/pull/60 and https://github.com/fhir-crucible/fhir_client/pull/59

**Comment by jawalonoski** [comment]
Merged STU3 fix. Waiting on DSTU2 (breaks Travis).

**Comment by arscan** [comment]
This has been merged and was deployed.
