### ISSUE TITLE
Unable to get MedicationStatement from Patient

### ISSUE THREAD

**Issue by yalestar** [fhir-crucible/fhir_client#63]
Firstly, thanks for providing this gem!

My issue is actually just a couple of questions, but I wasn't sure where else to put it.

1. If I have a reference to a `Patient` object, what's the best way to get one of its associated objects, `MedicationStatement` for instance? If it matters, I got the `Patient` reference thusly: `fhir_client.read(FHIR::Patient, patient_id, FHIR::Formats::ResourceFormat::RESOURCE_JSON_DSTU2).resource`

2. Does this client gem support OAuth2 authentication where you have only a client_id and an application ID, but no client_secret? Browsing the source, it looks like not, but I just wanted to confirm.

Much appreciated!

**Comment by yalestar** [comment]
I don't know whether this is the canonical way to do it, but I was able to get a MedicationStatement for a patient thusly:

`FHIR::MedicationStatement.search(patient: patient.id)`

**Comment by jawalonoski** [comment]
First, you're welcome! Thanks for using this gem!

1. There is no canonical way to do it... the way you used is probably best. Another way would be:
```ruby
fhir_client.search(FHIR::MedicationStatement, { :search=>{ :parameters=>{ 'patient'=> patient.id} } })
```
The later method allows you to add more precise options to your request that you probably don't need.

2. Yes, we support OAuth2. Try looking at our sample SMART app: https://github.com/fhir-crucible/crucible_smart_app to see how we've used fhir_client, with RestClient, and Sinatra to build a SMART-on-FHIR app. Hope this helps.

**Comment by yalestar** [comment]
I'll give that sample app a spin; thanks again for the help!
