### ISSUE TITLE
rest-client version requirements

### ISSUE THREAD

**Issue by EtienneDepaulis** [fhir-crucible/fhir_client#70]
Hello guys,

we noticed that you recently updated `rest-client` version requirements with a strict approach:
`spec.add_dependency 'rest-client', '~> 2.0'`
=> https://github.com/fhir-crucible/fhir_client/commit/844dc2e8613d994b84002478ddec22656594fbdf#diff-c2541be243f7010061e6644706359c34R29

This new requirement does not seems to be driven by code requirements. 

On our code base we have a very important gem requiring rest-client v1.8 so we are kinda stuck :/
We have a small PR to fix an other issue as well : https://github.com/honestica/fhir_client/commit/2a09a15bae9f617408d024986b6302196a3aa7c9

Thanks for your help

**Comment by jawalonoski** [comment]
We updated `rest-client` and `oauth2` recently when we added support for Ruby 2.4.

Please issue a pull request. If the PR passes Travis tests, then we'll consider downgrading the gem dependency.

**Comment by olbrich** [comment]
@EtienneDepaulis which gem is requiring rest-client 1.8?  It might make some sense to try to get that gem to update it's dependencies to use the newer version.

**Comment by jawalonoski** [comment]
The proposed PR #71 seems to have been abandoned. I'm closing this issue.
