### ISSUE TITLE
Logging is leaking credentials to logs

### ISSUE THREAD

**Issue by mtparet** [fhir-crucible/fhir_client#74]
For all requests, the gem records the request including headers with secrets in logs. https://github.com/fhir-crucible/fhir_client/blob/master/lib/fhir_client/client.rb#L334 
Should we set the logging level to debug for these logs (production environment should not run in debug) ? Or should we have a logging that remove/select the secrets/data ?

**Comment by jawalonoski** [comment]
I'm not sure which secrets are leaking under what conditions. If you'd like to submit a pull request to remove secrets data, we'd happily review it. I'm also open to changing the log level to debug.

**Comment by mtparet** [comment]
Thank you, I opened a PR to change the log level to debug for the request/response logging.
