### ISSUE TITLE
Gem Release

### ISSUE THREAD

**Issue by ajbeeson** [fhir-crucible/fhir_client#79]
I'm currently working on an integration with the smart health sandbox. I noticed that next_bundle was broken, but was fixed and merged to master. Is there a plan on releasing a new version of the gem.

**Comment by jawalonoski** [comment]
We're probably going to merge the `multiversion` branch before we release another gem.

In the meantime, if you'd like to use the updated version, you can temporarily do something like this in your `Gemfile`:

```
gem 'fhir_client', git: 'https://github.com/fhir-crucible/fhir_client.git', branch: 'multiversion'
```

Use the `master` or `multiversion` branch as you desire. Thanks for your patience until we release an updated gem!

**Comment by jawalonoski** [comment]
Fixed with latest gem release: https://github.com/fhir-crucible/fhir_client/releases/tag/v3.0.3
