### ISSUE TITLE
Logging strategy regression

### ISSUE THREAD

**Issue by EtienneDepaulis** [fhir-crucible/fhir_client#92]
Hello guys,

around January #74 by @mtparet was merged, changing the log levels (using `info` could leak sensitive information in the logs, `debug` for certain actions was proposed).

I recently checked the history of `client.rb` : https://github.com/fhir-crucible/fhir_client/commits/master/lib/fhir_client/client.rb and I noticed a commit by @jawalonoski reverting all those changes : 

![image](https://user-images.githubusercontent.com/639743/41119591-734ce7ca-6a93-11e8-9221-02f87d0c94a1.png)

I therefore wanted to know where you stand on this logging strategy. Was it a mistake or do you prefer the `info` level ? In this case, are you open to a suggestion to let the consumer sets the logging level ?

Thanks for your help

**Comment by jawalonoski** [comment]
Oh no, that was a mistake. Seems like the change was lost when I merged master into multi version... Could you resubmit the PR?

**Comment by EtienneDepaulis** [comment]
hi @jawalonoski, I checked again this morning and everything seems just fine, I must have been confused by our fork which is not up to date (I'm working on it). Sorry
