### ISSUE TITLE
Can this gem instantiate a new Patient object from json

### ISSUE THREAD

**Issue by bopritchard** [fhir-crucible/fhir_client#95]
Can this gem instantiate a new Patient object from json?

So it would look like.
json_string = "{ "resourceType": "Patient",  "id": "example", blah blah blah}"
patient = FHIR::Patient.new json_string

Possible? Thanks

**Comment by EtienneDepaulis** [comment]
Here you go:

```ruby
> patient_data = {resourceType: "Patient", id: "123"}
=> {:resourceType=>"Patient", :id=>"123"}
> patient = FHIR.from_contents(patient_data.to_json)
=> #<FHIR::Patient:0x00007f9a10f20ba0
 @active=nil,
 @address=[],
 @animal=nil,
 @birthDate=nil,
 @communication=[],
 @contact=[],
 @contained=[],
 @deceasedBoolean=nil,
 @deceasedDateTime=nil,
 @extension=[],
 @gender=nil,
 @generalPractitioner=[],
 @id="123",
 @identifier=[],
 @implicitRules=nil,
 @language=nil,
 @link=[],
 @managingOrganization=nil,
 @maritalStatus=nil,
 @meta=nil,
 @modifierExtension=[],
 @multipleBirthBoolean=nil,
 @multipleBirthInteger=nil,
 @name=[],
 @photo=[],
 @telecom=[],
 @text=nil>
> patient.id
=> "123"
```

**Comment by bopritchard** [comment]
I really appreciate the help. On a similar note, I'd like to be able to trap when an attempt to instantiate invalid data is made.
For instance, `FHIR.from_contents '{"asdf":"asdf"}'` returns the following `ERROR -- : Failed to deserialize JSON:`

But it doesn't raise an rescuable exception. Is there a way I can handle this? I might just be looking at it wrong. Thanks again

```
begin 
   FHIR.from_contents '{"asdf":"asdf"}'
rescue
   puts "error"
end
```

**Comment by arscan** [comment]
The current API does not raise exceptions on parse errors.  Instead, it will return `nil`.

```
asdf_resource = FHIR.from_contents '{"asdf": "asdf"}'

puts 'parse problem' if asdf_resource.nil?

```

If you would like it to behave that way, you could do something like this:

```
asdf_resource = FHIR.from_contents('{"asdf": "asdf"}') || raise
```

I think raising exceptions on invalid resources by default instead of returning `nil` would probably make more sense, and it would probably fix a whole class of problems in some of our test tools, but that's not how it is done right now.
