### ISSUE TITLE
Developers Seeking Advise for Working with FHIR

### ISSUE THREAD

**Issue by ndrwptrsn** [fhir-crucible/fhir_client#97]
I am an intern building a mobile app using a Rails API with the FHIR gem for the local hospital. I need to pull all the observations for a specific patient into our DB. So far I am able to pull what (I think) are all the observations (for the patient) from the sandbox like this:

```
client = FHIR::Client.new('http://r2.smarthealthit.org')
client.use_dstu2
patient_response = client.read(FHIR::Patient, '6638c5fe-0e89-442f-a970-2228d61b141c')
patient = patient_response.resource
observation_response = client.search(FHIR::Observation, search: { parameters: {patient: patient.id}})
observation_response.resource.entry.map(&:resource)
```

But I can't figure out how to pull specific observations and their values out. Specifically blood pressure data. It seems like it's a simple matter of knowing the key value pairs, i.e. observation_response.entry[0].systolic or something like that, but I'm having little luck. Forgive me if there is an obvious answer that I'm missing, but I've been stuck on this for awhile now.

Any advice would be greatly appreciated!

**Comment by jawalonoski** [comment]
A blood pressure observation looks a little different than other observations. It has two _component values_ rather than one value.

Consider this DSTU2 `Observation`:
```json
{
  "resourceType": "Observation",
  "id": "df1f4e7e-2f8a-48a2-8008-a797fe08f219",
  "status": "final",
  "category": {
    "coding": [
      {
        "system": "http://hl7.org/fhir/observation-category",
        "code": "vital-signs",
        "display": "vital-signs"
      }
    ],
    "text": "vital-signs"
  },
  "code": {
    "coding": [
      {
        "system": "http://loinc.org",
        "code": "55284-4",
        "display": "Blood Pressure"
      }
    ],
    "text": "Blood Pressure"
  },
  "subject": {
    "reference": "urn:uuid:d3b803c0-fdd9-44c4-b738-3c46cd5fd0e1"
  },
  "encounter": {
    "reference": "urn:uuid:e6dc6b6a-7d5f-4198-b46d-719c68383f84"
  },
  "effectiveDateTime": "2008-10-04T00:03:17-04:00",
  "issued": "2008-10-04T00:03:17.297-04:00",
  "component": [
    {
      "code": {
        "coding": [
          {
            "system": "http://loinc.org",
            "code": "8462-4",
            "display": "Diastolic Blood Pressure"
          }
        ],
        "text": "Diastolic Blood Pressure"
      },
      "valueQuantity": {
        "value": 78.71511169240652,
        "unit": "mmHg",
        "system": "http://unitsofmeasure.org",
        "code": "mmHg"
      }
    },
    {
      "code": {
        "coding": [
          {
            "system": "http://loinc.org",
            "code": "8480-6",
            "display": "Systolic Blood Pressure"
          }
        ],
        "text": "Systolic Blood Pressure"
      },
      "valueQuantity": {
        "value": 122.12419086536512,
        "unit": "mmHg",
        "system": "http://unitsofmeasure.org",
        "code": "mmHg"
      }
    }
  ]
}
```

Now, you can access the values with this code:
```ruby
# save the above observation in obs.json
json = File.open('obs.json','r:UTF-8',&:read)
observation = FHIR::DSTU2.from_contents(json)
puts observation.component[0].code.coding[0].code # 8462-4
puts observation.component[0].valueQuantity.value # 78.71511169240652
puts observation.component[1].code.coding[0].code # 8480-6
puts observation.component[1].valueQuantity.value # 122.12419086536512
```

Obviously, in your use-case you aren't going to access the observation from a file, you'll use the client as you are, but the principle is the same.

**Comment by jawalonoski** [comment]
Also, since you are using DSTU2, you should be using `FHIR::DSTU2::Patient` and `FHIR::DSTU2::Observation` otherwise the gem will try to deserialize with the STU3 version of FHIR and it will be lossy.

**Comment by ndrwptrsn** [comment]
Ah, this is awesome. Thank you for your help and quick response! Extracting data works now. Part of my confusion came from the fact that all the responses I get look like this:

```
#<FHIR::DSTU2::Observation:0x007fba15d34d08 @id="c4d57269-d76c-41a4-bcdc-3782fe2df0b2", @meta=#<FHIR::DSTU2::Meta:0x007fba15d345b0 @id=nil, @extension=[], @versionId="1", @lastUpdated="2018-05-07T13:41:04.817-04:00", @profile=[], @security=[], @tag=[#<FHIR::DSTU2::Coding:0x007fba15d34308 @id=nil, @extension=[], @system="https://smarthealthit.org/tags", @version=nil, @code="synthea-8-2017", @display=nil, @userSelected=nil>]>, @implicitRules=nil, @language=nil, @text=nil, @contained=[], @extension=[], @modifierExtension=[], @identifier=[], @status="final", @category=#<FHIR::DSTU2::CodeableConcept:0x007fba17803d00 @id=nil, @extension=[], @coding=[#<FHIR::DSTU2::Coding:0x007fba17803c10 @id=nil, @extension=[], @system="http://hl7.org/fhir/observation-category", @version=nil, @code="vital-signs", @display=nil, @userSelected=nil>], @text=nil>, @code=#<FHIR::DSTU2::CodeableConcept:0x007fba178037d8 @id=nil, @extension=[], @coding=[#<FHIR::DSTU2::Coding:0x007fba178036e8 @id=nil, @extension=[], @system="http://loinc.org", @version=nil, @code="8302-2", @display="Body Height", @userSelected=nil>], @text="Body Height">, @subject=#<FHIR::DSTU2::Reference:0x007fba17803170 @id=nil, @extension=[], @reference="Patient/6638c5fe-0e89-442f-a970-2228d61b141c", @display=nil>, @encounter=#<FHIR::DSTU2::Reference:0x007fba17802ef0 @id=nil, @extension=[], @reference="Encounter/652bee53-4b9a-4e44-a6ec-f24167270cd0", @display=nil>, @effectiveDateTime="2012-09-09T11:02:01-04:00", @effectivePeriod=nil, @issued="2012-09-09T11:02:01-04:00", @performer=[], @valueQuantity=#<FHIR::DSTU2::Quantity:0x007fba17802b80 @id=nil, @extension=[], @value=146.8519856189678, @comparator=nil, @unit="cm", @system="http://unitsofmeasure.org/", @code="cm">, @valueCodeableConcept=nil, @valueString=nil, @valueRange=nil, @valueRatio=nil, @valueSampledData=nil, @valueAttachment=nil, @valueTime=nil, @valueDateTime=nil, @valuePeriod=nil, @dataAbsentReason=nil, @interpretation=nil, @comments=nil, @bodySite=nil, @local_method=nil, @specimen=nil, @device=nil, @referenceRange=[], @related=[], @component=[]>
```

Instead of the clean, easy to read JSON you've shown here. Is there a resource for all the key value pairs associated with the various calls? We are also hoping to pull in medication data. Thanks again for the help and the gem!

**Comment by jawalonoski** [comment]
Well, you could always resort to some tricky ruby meta programming to get a list of attributes for any object:

```ruby
observation.methods - Object.methods
```

But you should be able to just use the list of fields from the FHIR specification:
http://hl7.org/fhir/DSTU2/resourcelist.html

Alternatively, you can use the ruby class definitions:
https://github.com/fhir-crucible/fhir_dstu2_models/tree/master/lib/fhir_dstu2_models/fhir/resources

You can also do something like:
```ruby
puts observation.to_json
```

**Comment by ndrwptrsn** [comment]
One more question: I'm now trying to pull all the observations and medications for a given set of patients. There seems to be a fetchAll operation in FHIR.js that retrieves the complete set of resources matching specific search criteria, is there some equivalent operation in this gem? The docs show how to get a bundle of patients, but it's not clear whether there is a way to get multiple specific patients, i.e. something like this:
```
reply = client.read_feed(FHIR::DSTU2::Patient, 'smart-1213208, 6638c5fe-0e89-442f-a970-2228d61b141c')
bundle = reply.resource
```
This request pulls way more patients than the two I want and I'm only getting metadata about them. Is there some way to get something like this to work?:
```
bundle.entry.each do |entry|
  patient = entry.resource
  puts patient.name[0].text
  puts patient.observations[0].component[0] etc
  puts patient.medications[0]
end
```

I'm thinking maybe there's some kind of bundle request like this:
```
bundle_response = client.search(FHIR::DSTU2::Bundle, search: 
  { parameters: 
    {observations: 
      {parameters: {patients: patient1.id, patient2.id}
      }
    {medications:
      {parameters: {patients: patient1.id, patient2.id}
    }
  }
})
```
But I'm not sure if this is even a tenable approach. Am I wrong in thinking all observations and medications can be pulled for a set of patients at once? I'd like to keep the number of requests to a minimum.

Forgive me if this is a basic question, I'm new to coding and I've only been working with FHIR for a few weeks so I'm having a hard time putting the HL7/FHIR documentation into practice. I don't know what I don't know. Any advice would be greatly appreciated!

**Comment by dindrala** [comment]
@jawalonoski I am also having this same issue of trying to pull all the observations and medications for a given set of patients and not being able to. Any help would be super appreciated. Working under a tight deadline.

**Comment by jawalonoski** [comment]
### Everything
If you want to retrieve the entire patient record, you can use the [$everything](http://hl7.org/fhir/patient-operations.html#everything) operation.
```
GET /Patient/1/$everything
```
Using the `fhir_client` gem:
```ruby
reply = client.fetch_patient_record(1)
```

### Search
If you want to search a resource by patients 1 and 2, you can do something like this:

```
GET /Observation?patient=1,2
```
Using the `fhir_client` gem:
```ruby
reply = client.search(FHIR::DSTU2::Observation, { :search => { :parameters => { 'patient' => '1,2' }}})
```
